steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/custom_containers/aivc:latest', 'environments/custom_containers/aivc']
options:
  machineType: 'N1_HIGHCPU_32'
images:
  - 'gcr.io/$PROJECT_ID/custom_containers/aivc:latest'
