apiVersion: batch/v1
kind: Job
metadata:
  name: {{ submission.job_name }}
  labels:
    id: "{{ submission.id }}"
    task: "{{ submission.task.name }}"
    phase: "{{ submission.phase.name }}"
    team: "{{ submission.team.username }}"
spec:
  template:
    metadata:
      labels:
        id: "{{ submission.id }}"
        task: "{{ submission.task.name }}"
        phase: "{{ submission.phase.name }}"
        team: "{{ submission.team.username }}"
    spec:
      initContainers:
      - name: decode
        image: "gcr.io/clic-215616/decoding:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "{{ submission.phase.memory }}M"
            cpu: {{ submission.phase.cpu }}{% if submission.docker_image.gpu %}
            nvidia.com/gpu: 1{% endif %}
          limits:
            memory: "{{ submission.phase.memory|add:500 }}M"
            cpu: {{ submission.phase.cpu }}{% if submission.docker_image.gpu %}
            nvidia.com/gpu: 1{% endif %}
        command: [
          "python3",
          "/code/decode.py",{% if debug %}
          "--debug",{% endif %}
          "--id", "{{ submission.id }}",
          "--exec_dir", "/var/lib/docker/submissions"]
        securityContext:
          capabilities: {}
          privileged: true
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/var/run/secret/cloud.google.com/service-account.json"
        envFrom:
          - secretRef:
              name: cloudsql
          - secretRef:
              name: buckets
        volumeMounts:
          - name: clic-sa-key-volume
            mountPath: "/var/run/secret/cloud.google.com"
          - name: docker-sock
            mountPath: "/var/run/docker.sock"
          - name: executable-volume
            mountPath: "/var/lib/docker"
          - name: code-volume
            mountPath: "/code"
      containers:
      - name: evaluate
        image: "gcr.io/clic-215616/evaluation"
        resources:
          requests:
            cpu: 1
            memory: "2G"{% if submission.docker_image.gpu %}
            nvidia.com/gpu: 1{% endif %}
          limits:
            memory: "4G"
            cpu: 1{% if submission.docker_image.gpu %}
            nvidia.com/gpu: 1{% endif %}
        command: [
          "python3",
          "/code/evaluate.py",{% if debug %}
          "--debug",{% endif %}
          "--id", "{{ submission.id }}",
          "--metrics", "PSNR", "MSSSIM"]
        securityContext:
          capabilities: {}
          privileged: true
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/var/run/secret/cloud.google.com/service-account.json"
        envFrom:
          - secretRef:
              name: cloudsql
          - secretRef:
              name: buckets
        volumeMounts:
          - name: clic-sa-key-volume
            mountPath: "/var/run/secret/cloud.google.com"
          - name: code-volume
            mountPath: "/code"
      restartPolicy: Never
      volumes:
        - name: clic-sa-key-volume
          secret:
            secretName: clic-sa-key
        - name: docker-sock
          hostPath:
            path: "/var/run/docker.sock"
        - name: executable-volume
          hostPath:
            path: "/var/lib/docker"
        - name: code-volume
          configMap:
            name: code
  backoffLimit: 0
